User.create(name: "David")
User.create(name: "Kevin")
User.create(name: "Robert")
User.create(name: "Jacob")
User.create(name: "Ian")

Project.create(title: "Ruby Beginner",description: "Basics of ruby", due_date: "05/03/2019" )
Project.create(title: "Ruby Intermediate",description: "Harder ruby", due_date: "05/20/2019" )
Project.create(title: "Ruby Advanced",description: "Final stage of Ruby", due_date: "06/07/2019" )
Project.create(title: "Java Beginner",description: "Basics of java", due_date: "06/19/2019" )
Project.create(title: "Java intermediate",description: "Harder java", due_date: "06/27/2019" )
Project.create(title: "Java advanced",description: "Final stage of Java", due_date: "07/03/2019" )
Project.create(title: "Python Beginner",description: "Basics of python", due_date: "07/10/2019" )
Project.create(title: "Python intermediate:r",description: "Harder python", due_date: "07/16/2019" )
Project.create(title: "Python Advanced",description: "Final stage of python", due_date: "07/27/2019" )
Project.create(title: "Bonus",description: "all material", due_date: "08/02/2019" )

#user 1 (David)
Commit.create(commit_message: "done", commit_date: "05/03/2019", on_time: true, user_id: 1, project_id: 1)
Commit.create(commit_message: "finished", commit_date: "05/20/2019", on_time: true, user_id: 1,project_id: 2)
Commit.create(commit_message: "easiest", commit_date: "06/10/2019", on_time: true, user_id: 1,project_id: 3)
Commit.create(commit_message: "getting harder", commit_date: "06/19/2019", on_time: true, user_id: 1,project_id: 4)
Commit.create(commit_message: "I need help", commit_date: "06/30/2019", on_time: true, user_id: 1,project_id: 5)
Commit.create(commit_message: "follow the readme", commit_date: "07/03/2019", on_time: true, user_id: 1,project_id: 6)
Commit.create(commit_message: "done", commit_date: "07/15/2019", on_time: true, user_id: 1,project_id: 7)
Commit.create(commit_message: "complete", commit_date: "07/16/2019", on_time: true, user_id: 1,project_id: 8)
# Commit.create(commit_message: "I know it all!", commit_date: "07/27/2019", on_time: true, 1,9)

#user2 (kevin)
Commit.create(commit_message: "first complettion", commit_date: "05/15/2019", on_time: true, user_id: 2, project_id: 1)
Commit.create(commit_message: "on a roll", commit_date: "05/20/2019", on_time: true, user_id: 2, project_id: 2)
Commit.create(commit_message: "slowing down", commit_date: "06/07/2019", on_time: true, user_id: 2, project_id: 3)
Commit.create(commit_message: "this one is late", commit_date: "06/19/2019", on_time: true, user_id: 2, project_id: 4)
Commit.create(commit_message: "on a roll for lates", commit_date: "06/27/2019", on_time: true, user_id: 2, project_id: 5)
Commit.create(commit_message: "complete", commit_date: "07/5/2019", on_time: true, user_id: 2, project_id: 6)
Commit.create(commit_message: "finished", commit_date: "07/10/2019", on_time: true, user_id: 2, project_id: 7)
Commit.create(commit_message: "I'm done", commit_date: "07/16/2019", on_time: true, user_id: 2, project_id: 8)
Commit.create(commit_message: "Wooooooo!", commit_date: "07/27/2019", on_time: true, user_id: 2, project_id: 9)

#user3 (Robert)
Commit.create(commit_message: "easy", commit_date: "05/03/2019", on_time: true, user_id: 3, project_id: 1)
Commit.create(commit_message: "harder", commit_date: "05/25/2019", on_time: true, user_id: 3, project_id: 2)
Commit.create(commit_message: "done", commit_date: "06/18/2019", on_time: true, user_id: 3, project_id: 3)
# Commit.create(commit_message: "done", commit_date: "date", on_time: true, user_id: 3, project_id: 4)
# Commit.create(commit_message: "done", commit_date: "date", on_time: true, user_id: 3, project_id: 5)
# Commit.create(commit_message: "done", commit_date: "date", on_time: true, user_id: 3, project_id: 6)
Commit.create(commit_message: "took a long break", commit_date: "07/10/2019", on_time: true, user_id: 3, project_id: 7)
Commit.create(commit_message: "skipped java", commit_date: "07/18/2019", on_time: true, user_id: 3, project_id: 8)
Commit.create(commit_message: "yay!", commit_date: "07/27/2019", on_time: true, user_id: 3, project_id: 9)

#user4 (Jacob)
Commit.create(commit_message: "first!", commit_date: "05/03/2019", on_time: true, user_id: 4, project_id: 1)
Commit.create(commit_message: "gettign harder", commit_date: "05/21/2019", on_time: true, user_id: 4, project_id: 2)
# Commit.create(commit_message: "done", commit_date: "date", on_time: true, user_id: 4, project_id: 3)
Commit.create(commit_message: "took a while", commit_date: "06/19/2019", on_time: true, user_id: 4, project_id: 4)
Commit.create(commit_message: "not bad", commit_date: "06/27/2019", on_time: true, user_id: 4, project_id: 5)
Commit.create(commit_message: "that was hard", commit_date: "07/03/2019", on_time: true, user_id: 4, project_id: 6)
# Commit.create(commit_message: "done", commit_date: "date", on_time: true, user_id: 4, project_id: 7)
Commit.create(commit_message: "no beginner needed", commit_date: "07/16/2019", on_time: true, user_id: 4, project_id: 8)
Commit.create(commit_message: "all done", commit_date: "07/27/2019", on_time: true, user_id: 4, project_id: 9)

#user5 (ian)
Commit.create(commit_message: "started from the bottom", commit_date: "05/03/2019", on_time: true, user_id: 5, project_id: 1)
Commit.create(commit_message: "slowly climbing", commit_date: "05/20/2019", on_time: true, user_id: 5, project_id: 2)
Commit.create(commit_message: "keep climbing", commit_date: "06/07/2019", on_time: true, user_id: 5, project_id: 3)
Commit.create(commit_message: "this is too hard", commit_date: "06/19/2019", on_time: true, user_id: 5, project_id: 4)
# Commit.create(commit_message: "done", commit_date: "date", on_time: true, user_id: 5, project_id: 5)
# Commit.create(commit_message: "done", commit_date: "date", on_time: true, user_id: 5, project_id: 6)
# Commit.create(commit_message: "done", commit_date: "date", on_time: true, user_id: 5, project_id: 7)
# Commit.create(commit_message: "done", commit_date: "date", on_time: true, user_id: 5, project_id: 8)
# Commit.create(commit_message: "done", commit_date: "date", on_time: true, user_id: 5, project_id: 9)
